### PR TITLE
Check command

### PR DESCRIPTION
**Pull request by msabramo**
Some fixes for your `check` command.
- Normalize names to lowercase
- Tell `get_installed_distributions` not to skip any packages like `setuptools`, etc.
##### Before

```
$ pip check
pdbpp 0.7.2 requires pygments, which is not installed.
bpython 0.13.1 requires pygments, which is not installed.
devpi-web 2.2.2 requires pygments, which is not installed.
distribute 0.7.3 requires setuptools, which is not installed.
Jinja2 2.7.3 requires markupsafe, which is not installed.
pyramid 1.5.2 requires setuptools, which is not installed.
pyramid 1.5.2 requires zope.deprecation, which is not installed.
waitress 0.8.9 requires setuptools, which is not installed.
zope.interface 4.1.1 requires setuptools, which is not installed.
```
##### After

```
$ pip check
pyramid 1.5.2 requires zope.deprecation, which is not installed.
```

The latter is correct in my situation because my virtualenv had `Pygments` and `setuptools` installed but not `zope.deprecation`.

### CODE REVIEW

**Comment by Wilfred** [comment]
Thanks! Would you mind adding a test for these cases?

**Comment by msabramo** [comment]
OK, I added a test but for some reason I can't get the tests to run locally and the Travis CI fails for your fork too.

I'm flying blind here, unable to test my own changes. Can you please try it and make any small mods necessary to get it working?

**Comment by msabramo** [comment]
I think the problem is that your branch is quite old and needs to be rebased on origin/develop.

**Comment by Wilfred** [comment]
Thanks for following up on this. It looks like you've sent a fixed PR anyway -- do you need anything from me?

**Comment by msabramo** [comment]
Nah, I think because I sent a fixed PR, that makes it a little easier and you still get credit, because you are the original author of the commit in git.

So I think we're good.

Oh one thing you could do is review my fixed PR; the more review it gets, the better the chance of it getting merged by a committer. https://github.com/pypa/pip/pull/2492

**Pull request closed without merging**
